FROM python:3.7-slim

RUN BUILD_DEPS='build-essential libpq-dev python3-dev' \
    && apt-get update \
    && apt-get install -y --no-install-recommends ${BUILD_DEPS} postgresql \
    && mkdir /src \
    && useradd -ms /bin/bash -d /src webmon

COPY webmon /src/webmon
COPY tests /src/tests
COPY setup.py /src/setup.py

RUN pip3.7 install '/src[dev]' \
    && chown -R webmon /src

USER webmon
WORKDIR /src
