FROM python:3.7-slim

RUN mkdir /src

COPY webmon /src/webmon
COPY tests /src/tests
COPY setup.py /src/setup.py

RUN BUILD_DEPS='build-essential libpq-dev python3-dev' \
    && apt-get update \
    && apt-get install -y --no-install-recommends ${BUILD_DEPS} postgresql \
    && pip3.7 install '/src[dev]' \
    && useradd -ms /bin/bash -d /src webmon

USER webmon
WORKDIR /src

